# Generated by Django 3.2.21 on 2023-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odms', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('mothername', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('organ', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=20)),
                ('aadharnumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('emergencynumber', models.CharField(max_length=10)),
                ('add', models.TextField()),
            ],
        ),
    ]
