# Generated by Django 3.2.21 on 2023-11-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odms', '0003_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='religion',
        ),
    ]
