# Generated by Django 3.1.4 on 2023-12-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odms', '0005_auto_20231211_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('msg', models.TextField()),
            ],
        ),
    ]
